---
title: "Data Viewer"
author: "Esa Turkulainen"
date: "7.4.2021"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_knit$set(root.dir = "~/CRP_enrichment") # set working directory
library(dplyr)
library(ggplot2)
source("~/CRP_enrichment/src/funcs.R") # load our helper functions
```

```{r load_data, echo = FALSE}
# .rdata by Sofie Ekroos, 2021

# Load data on individual donations
load("~/CRP_enrichment/data/r02.fd.bd.all.rdata") # outputs an object called "output" into the environment
indv_donations <- output

# Load FinDonor demographic data
load("~/CRP_enrichment/data/r02ds.donorData.rdata") # outputs an object called "output" into the environment
donorpop <- output 

# Load THL data
# Sofie: thldalta.rdata contains all five THL cohorts, extract FINRISK97 and Health2000 from the others
load("~/CRP_enrichment/data/thldata.rdata")
fr1997 <- thldata$fr1997
h2000 <- thldata$h2000

# Remove leftovers
rm(output)
rm(thldata)
```

```{r crp_ferr_all_nonlog, warning = FALSE}
p1 <- ggplot(data = fr1997, aes(x = FERRITIN, y = CRP)) + 
    geom_point() +
    theme_minimal() +
    labs(title = "FINRISK97 | CRP x Ferritin",
         subtitle = "No transformation",
         x = "Ferritin",
         y = "CRP")
p1log <- ggplot(data = fr1997, aes(x = log(FERRITIN), y = log(CRP))) + 
    geom_point() +
    theme_minimal() +
    labs(title = "FINRISK97 | CRP x Ferritin",
         subtitle = "Log transformation",
         x = "Ferritin",
         y = "CRP")
p2 <- ggplot(data = h2000, aes(x = FERRITIINI, y = CRP)) + 
    geom_point() +
    theme_minimal() +
    labs(title = "Health2000 | CRP x Ferritin",
         subtitle = "No transformation",
         x = "Ferritin",
         y = "CRP")
p2log <- ggplot(data = h2000, aes(x = log(FERRITIINI), y = log(CRP))) + 
    geom_point() +
    theme_minimal() +
    labs(title = "Health2000 | CRP x Ferritin",
         subtitle = "Log transformation",
         x = "Ferritin",
         y = "CRP")
p3 <- ggplot(data = indv_donations, aes(x = Ferritin, y = CRP)) + 
    geom_point() +
    theme_minimal() +
    labs(title = "FinDonor longitudinal | CRP x Ferritin",
         subtitle = "No transformation, CRP imputed <3, CRP measurements are integers",
         x = "Ferritin",
         y = "CRP")
p3log <- ggplot(data = indv_donations, aes(x = log(Ferritin), y = log(CRP))) + 
    geom_point() +
    theme_minimal() +
    labs(title = "FinDonor longitudinal | CRP x Ferritin",
         subtitle = "Log transformation, CRP imputed <3, CRP measurements are integers",
         x = "Ferritin",
         y = "CRP")
multiplot(p1, p2, p3, p1log, p2log, p3log, cols = 2)
```
```{r}
mean_by_quantile <- function(df, by = "Ferritin", var2 = "CRP", n = 4){
    data <- df[, c(by, var2)]
    # tbd
}
```

